#!/usr/bin/env bash

# Iterates the current directory and calls git add, commit and push
# All repositories are getting pushed to the branch named 'develop'
#
#	You can set another commit message rather than 'work in progress' by calling './git_push_all "A commit message"'
#
# 	git add .;
# 	git commit -m "work in progress";
# 	git push origin develop;
#

source .functions
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ "$#" -ne 1 ]; then
	echo "Usage: git_push_all <commit message (optional; the default is 'work in progress')>"
	COMMIT_MSG='work in progress';
else
	COMMIT_MSG="${1}";
fi

echo "${COMMIT_MSG}"


git add .;
git commit -m "${COMMIT_MSG}";
git push origin develop;
pwd
