#!/usr/bin/env bash

# Calls git add, commit and push for the repository in the current directory
#
# 	git add .;
# 	git commit -m "work in progress";
# 	git push origin develop;
#

source .functions
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ "$#" -eq 0 ]; then
	echo_warn "Using: git push develop 'work in progress'"
	BRANCH="develop"
	COMMIT_MSG="work in progress"
	# echo "Usage: push <branch, commit message>"
	# exit 1
elif [ "$#" -eq 1 ]; then
	echo_warn "Using: git push ${1} 'work in progress'"
	BRANCH="${1}"
	COMMIT_MSG="work in progress"
elif [ "$#" -eq 2 ]; then
	echo_warn "Using: git push ${1} '${2}'"
	BRANCH="${1}"
	COMMIT_MSG="${2}"
fi

echo_ok "Adding all files"
git add .;

echo_ok "Commiting with message '${COMMIT_MSG}'"
git commit -m "${COMMIT_MSG}";

echo_ok "Pushing to branch ${BRANCH}"
git push origin "${BRANCH}";
